# Generated by Django 5.1 on 2024-08-14 08:50

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="mobile_phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[accounts.validators.validate_mobile_phone],
                verbose_name="mobile phone",
            ),
        ),
    ]
