# Generated by Django 5.1 on 2024-08-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mobileverify",
            options={
                "verbose_name": "mobile verify",
                "verbose_name_plural": "mobile verify",
            },
        ),
        migrations.AlterModelTable(
            name="mobileverify",
            table="mobile_verify",
        ),
    ]
