# Generated by Django 5.1 on 2024-08-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_mobileverify_options_alter_mobileverify_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobileverify",
            name="code",
            field=models.CharField(max_length=9, verbose_name="code"),
        ),
    ]
