# Generated by Django 5.1 on 2024-08-14 08:40

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
                ("update_at", django_jalali.db.models.jDateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    django_jalali.db.models.jDateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                (
                    "nation_code",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="National Code"
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Mobile Phone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "is_legal",
                    models.BooleanField(
                        default=False,
                        help_text="Check this box if you are a legal entity",
                        verbose_name="Is Legal",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "personal shop",
                "verbose_name_plural": "personal shop",
                "db_table": "personal_shop",
            },
        ),
        migrations.CreateModel(
            name="RecordProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
                ("update_at", django_jalali.db.models.jDateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    django_jalali.db.models.jDateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "product_amount",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "is_delivery",
                    models.BooleanField(default=True, verbose_name="Is Delivery"),
                ),
            ],
            options={
                "verbose_name_plural": "record products",
                "db_table": "record_product",
            },
        ),
        migrations.CreateModel(
            name="CertificateShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
                ("update_at", django_jalali.db.models.jDateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    django_jalali.db.models.jDateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "is_active_image",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="image_certificate_inventory",
                        to="images.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate shop",
                "verbose_name_plural": "Certificate shop",
                "db_table": "certificate_shop",
            },
        ),
        migrations.CreateModel(
            name="ProfileShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
                ("update_at", django_jalali.db.models.jDateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    django_jalali.db.models.jDateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Is Active"),
                ),
                (
                    "is_verify",
                    models.BooleanField(default=False, verbose_name="Is Verify"),
                ),
                ("bio", models.TextField(blank=True, null=True, verbose_name="Bio")),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "economy_code",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Economy Code",
                    ),
                ),
                (
                    "level_type_of_activity",
                    models.TextField(
                        blank=True, null=True, verbose_name="Type of Activity"
                    ),
                ),
                (
                    "company_date_registration",
                    models.DateField(
                        blank=True, null=True, verbose_name="Company Registration Date"
                    ),
                ),
                (
                    "sheba_number",
                    models.CharField(
                        blank=True,
                        max_length=24,
                        null=True,
                        verbose_name="Sheba Number or cart number",
                    ),
                ),
                ("is_complete_profile", models.BooleanField(default=False)),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificate_inventory",
                        to="inventory.certificateshop",
                    ),
                ),
                (
                    "identity_inventory",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profile_inventory",
                        to="inventory.personalshop",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="image_inventory",
                        to="images.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile shop",
                "verbose_name_plural": "Profile shop",
                "db_table": "profile_shop",
            },
        ),
    ]
