# Generated by Django 5.1 on 2024-08-14 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profile_record_product",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="recordproduct",
            name="profile_inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profile_record_product",
                to="inventory.profileshop",
            ),
        ),
    ]
